@repo = matleclaire/gh-actions-example
@GITHUB_TOKEN = your_token

POST https://api.github.com/repos/{{repo}}/dispatches
Accept: application/vnd.github+json
Authorization: Bearer {{GITHUB_TOKEN}}
X-GitHub-Api-Version: 2022-11-28

{
  "event_type": "custom-event-type",
  "client_payload": {
    "unit": false,
    "integration": true
  }
}
