name: java app build

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  packages: write

jobs:
  build:
    name: build java app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/build-java
        with:
          working-directory: ./java-app