name: java app build with custom action

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: build java app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - uses: ./.github/actions/code-quality-java
        with:
          working-directory: ./java-app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}